sudo: required
dist: trusty
language: node_js
node_js:
  - "6.14.3"

before_script:
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb -y
  - mongo < test-create-admin-user-mongo.js
  - sudo service mongodb stop
  - sudo bash -c "echo 'auth = true' >> /etc/mongodb.conf"
  - sudo service mongodb start
  - cat /var/log/mongodb/mongodb.log
  - ls /var/lib/mongodb/
  - sleep 15
  - mongo -u "test" -p "test" --authenticationDatabase "admin" < test-create-db-user-mongo.js

script:
  - npm install
  - npm test
