sudo: required
dist: trusty
language: node_js
node_js:
  - "4.8.7"

before_script:
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org -y
  - sudo apt-get install mongodb-org=2.6.10 mongodb-org-server=2.6.10 mongodb-org-shell=2.6.10 mongodb-org-mongos=2.6.10 mongodb-org-tools=2.6.10 -y

script:
  - sudo npm install
  - npm test
