version: '3'
services:
  nota:
    build: .
    ports:
     - "3000:3000"
    environment:
      - DATABASEURI=mongodb://mongo/nota-test
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
    depends_on:
      - "mongo"
    container_name: nota-backend
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    # image: "nota-db:latest"
    ports:
     - "27018:27018"
    container_name: nota-mongodb
