name: ESLINT

# This workflow is triggered on pushes to this repository
on:
  push:
    branches:
    - '*'
    paths:
    - '*' # Run workflow for all paths, later determine to run workflow only on javascript file changes.

# Define our jobs
jobs:
  lint:
    name: Linter # Job name
    runs-on: ubuntu-16.04 # Run on Ubuntu version 16.04.
    steps:
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint
      run: ./node_modules/.bin/eslint ../*
